FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .

ENV CGO_ENABLED=0

RUN go build -o /catmonitor ./cmd/catmonitor
RUN go build -o /dfee ./features/dfee
RUN go build -o /web ./features/web

FROM alpine:latest

RUN apk add --no-cache ipmitool smartmontools util-linux dmidecode

COPY --from=builder /catmonitor /usr/local/bin/catmonitor
COPY --from=builder /dfee /usr/local/bin/dfee
COPY --from=builder /web /usr/local/bin/web
COPY docker/catmonitor.yaml /etc/catmonitor/catmonitor.yaml
COPY configs/metrics.yaml /etc/catmonitor/metrics.yaml
COPY features/web/metrics.yaml /features/web/metrics.yaml
COPY features/dfee/metrics.yaml /features/dfee/metrics.yaml
COPY features/health/metrics.yaml /features/health/metrics.yaml
COPY features/dfee/grafana-dashboard.json /features/dfee/grafana-dashboard.json
COPY features/dfee/USAGE.md /features/dfee/USAGE.md

ENTRYPOINT ["/usr/local/bin/catmonitor", "daemon", "--config", "/etc/catmonitor/catmonitor.yaml"]
